services:
  keycloack:
    image: quay.io/keycloak/keycloak
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak_data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev']

  rabbitmq:
    image: rabbitmq:4.1.0-beta.3-management
    container_name: 'pets-crud-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
  
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes: 
      - '/:/host:ro'
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: root
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    user: root
    image: grafana/grafana-oss:latest
    ports:
      - '5000:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana